2025-03-04 18:43:17,260 ERROR: Exception on /reset_password_request [POST] [in C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\app\routes.py", line 159, in reset_password_request
    send_password_reset_email(user)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\app\email.py", line 19, in send_password_reset_email
    html_body=render_template('email/reset_password.html', token=token))
              ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Olga\PycharmProjects\Flask_book\app\templates\email\reset_password.html", line 8, in top-level template code
    <p>Dear {{ user.username }},</p>
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
